2019-12-06 14:39:26,731 [38] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 14:41:08,756 [31] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 14:46:02,683 [17] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 14:46:23,106 [12] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 14:56:03,804 [36] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 14:56:23,008 [34] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 14:58:54,325 [42] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 15:00:59,985 [36] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 15:02:54,589 [42] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 15:03:09,071 [13] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 15:03:49,975 [47] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Conflicto de tipos de operandos: text es incompatible con datetime
   en Mantenimiento.DataAccess.FallasDData.<InsertFallasD>d__2.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\FallasDData.cs:línea 122
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.FallasDLogic.<InsertFallasD>d__3.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\FallasDLogic.cs:línea 109
2019-12-06 17:08:50,799 [24] ERROR [en JBLV.Log.Log.RegistrarLog(NivelLog nivel, Exception ex)] 
System.Exception: Instrucción DELETE en conflicto con la restricción REFERENCE "FK_ID_tb_Sistema_Mant". El conflicto ha aparecido en la base de datos "BDALM2019_NIC", tabla "dbo.tb_SubSistema_Mant", column 'ID_tb_Sistema_Mant'.
Se terminó la instrucción.
   en Mantenimiento.DataAccess.SistemasData.<DeleteSistemas>d__5.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.DataAccess\SistemasData.cs:línea 213
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Mantenimiento.BusinessLayer.SistemasLogic.<DeleteSistemas>d__1.MoveNext() en D:\PROYECTOS A IMPLEMENTAR\MANTENIMIENTO NUEVO\Template\Template.BusinessLayer\SistemasLogic.cs:línea 63
